"""Bundle the plugin: src/*.js -> code.js; data/screens-*.json -> ui.html (the plugin window).

1. Serve the prototypes (python3 -m http.server 4001 --directory design/concept-prototypes)
2. Re-capture screens (see README)
3. python3 design/figma-plugin/build.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
# Redesign (live app tabs): Live screenshots + Balanced + Playful. Calm Core (A) was dropped on Oct 5.
data = json.loads((HERE / "data" / "redesign.json").read_text()) if (HERE / "data" / "redesign.json").exists() else []
# Only the Live screenshots come from captured data; every other screen is built from components in the plugin.
data = [d for d in data if d.get("concept") == "Live"]
# Sample pet photo (Max) for the photo slots in components.
import base64
photo = HERE.parent / "concept-prototypes" / "redesign" / "img" / "pet0.jpg"
if photo.exists():
    data.insert(0, {"concept": "_samples", "label": "", "screens": [], "images": {"max": "data:image/jpeg;base64," + base64.b64encode(photo.read_bytes()).decode()}})
code = "\n".join(["/* Generated by build.py — edit src/, not this file. */"] + [(HERE / "src" / f).read_text() for f in ("screens.js", "components.js", "foundations.js", "compose.js", "main.js")])
(HERE / "code.js").write_text(code)
payload = json.dumps(data, separators=(",", ":")).replace("</", "<\\/")
ui = (HERE / "src" / "ui.html").read_text().replace("/*DATA*/null", payload)
(HERE / "ui.html").write_text(ui)
print(f"code.js {len(code) // 1024} KB · ui.html {len(ui) // 1024} KB · {sum(len(d['screens']) for d in data)} screens")
